import {
  Activity,
  AlertCircle,
  AlertTriangle,
  BarChart3,
  Bell,
  Bot,
  Brain,
  Boxes,
  Clock,
  Cloud,
  Code,
  Cpu,
  CreditCard,
  ArrowDownUp,
  Database,
  DollarSign,
  RefreshCw,
  Download,
  Eye,
  FileText,
  FileWarning,
  FlaskConical,
  Gauge,
  GitBranch,
  Globe,
  Image,
  Key,
  LayoutDashboard,
  Link,
  Lock,
  Mail,
  Map,
  MessageCircle,
  MessageSquare,
  Mic,
  Package,
  Pen,
  Play,
  Plug,
  Power,
  Receipt,
  ScrollText,
  Shield,
  ShieldAlert,
  Skull,
  Settings,
  Smartphone,
  Sparkles,
  Tag,
  TrendingDown,
  TrendingUp,
  Users,
  Video,
  Wallet,
  Landmark,
  Zap,
  CircleDollarSign,
  Search,
  Target,
  Barcode,
  type LucideIcon,
} from "lucide-react";

export interface NavChild {
  id: string;
  label: string;
  icon: LucideIcon;
}

export interface NavGroup {
  id: string;
  label: string;
  icon: LucideIcon;
  children: NavChild[];
}

export const MANAGER_NAV: NavGroup[] = [
  {
    id: "dashboard",
    label: "API & AI Dashboard",
    icon: LayoutDashboard,
    children: [
      { id: "dashboard-total", label: "Total APIs Connected", icon: Plug },
      { id: "dashboard-active", label: "Active APIs", icon: Power },
      { id: "dashboard-inactive", label: "Inactive APIs", icon: Power },
      { id: "dashboard-ai-vs-non", label: "AI APIs vs Non-AI APIs", icon: Bot },
      { id: "dashboard-today", label: "Today Usage", icon: Clock },
      { id: "dashboard-monthly", label: "Monthly Cost", icon: DollarSign },
      { id: "dashboard-wallet", label: "Wallet Balance", icon: Wallet },
      { id: "dashboard-risk", label: "Risk Alerts", icon: AlertTriangle },
    ],
  },
  {
    id: "ai-api",
    label: "AI API Management",
    icon: Bot,
    children: [
      { id: "ai-openai", label: "OpenAI", icon: Brain },
      { id: "ai-vision", label: "Vision AI", icon: Eye },
      { id: "ai-voice", label: "Voice / TTS / STT", icon: Mic },
      { id: "ai-image", label: "Image Generation", icon: Image },
      { id: "ai-video", label: "Video AI", icon: Video },
      { id: "ai-nlp", label: "NLP / Chat AI", icon: MessageSquare },
      { id: "ai-custom", label: "Custom AI Models", icon: Cpu },
    ],
  },
  {
    id: "external-api",
    label: "External API Management",
    icon: Plug,
    children: [
      { id: "ext-payment", label: "Payment APIs", icon: CreditCard },
      { id: "ext-sms", label: "SMS APIs", icon: MessageCircle },
      { id: "ext-email", label: "Email APIs", icon: Mail },
      { id: "ext-whatsapp", label: "WhatsApp APIs", icon: MessageCircle },
      { id: "ext-maps", label: "Maps APIs", icon: Map },
      { id: "ext-cloud", label: "Cloud APIs", icon: Cloud },
      { id: "ext-analytics", label: "Analytics APIs", icon: BarChart3 },
    ],
  },
  {
    id: "usage-monitor",
    label: "API Usage Monitor",
    icon: Activity,
    children: [
      { id: "usage-rps", label: "Requests per Second", icon: Gauge },
      { id: "usage-per-user", label: "Requests per User", icon: Users },
      { id: "usage-per-product", label: "Requests per Product", icon: Package },
      { id: "usage-per-role", label: "Requests per Role", icon: Users },
      { id: "usage-failed", label: "Failed Requests", icon: AlertCircle },
      { id: "usage-latency", label: "Latency Monitor", icon: Clock },
    ],
  },
  {
    id: "product-api",
    label: "Product-wise API Control",
    icon: Package,
    children: [
      { id: "product-mapping", label: "Product → API Mapping", icon: Plug },
      { id: "product-enable", label: "Enable APIs per Product", icon: Power },
      { id: "product-disable", label: "Disable APIs per Product", icon: Power },
      { id: "product-cost", label: "Product API Cost Breakdown", icon: DollarSign },
      { id: "product-graph", label: "Product Usage Graph", icon: BarChart3 },
    ],
  },
  {
    id: "role-api",
    label: "Role-wise API Control",
    icon: Users,
    children: [
      { id: "role-admin", label: "Admin API Access", icon: Shield },
      { id: "role-reseller", label: "Reseller API Access", icon: Users },
      { id: "role-franchise", label: "Franchise API Access", icon: Users },
      { id: "role-developer", label: "Developer API Access", icon: Cpu },
      { id: "role-user", label: "User API Access", icon: Users },
    ],
  },
  {
    id: "wallet",
    label: "Wallet System",
    icon: Wallet,
    children: [
      { id: "wallet-central", label: "Central Wallet", icon: Wallet },
      { id: "wallet-balance", label: "Wallet Balance", icon: DollarSign },
      { id: "wallet-upi", label: "UPI Add Money", icon: CreditCard },
      { id: "wallet-ledger", label: "Wallet Ledger", icon: FileText },
      { id: "wallet-hold", label: "Wallet Hold Amount", icon: Lock },
      { id: "wallet-lock", label: "Wallet Lock / Unlock", icon: Lock },
    ],
  },
  {
    id: "billing",
    label: "Billing Engine",
    icon: Receipt,
    children: [
      { id: "billing-api", label: "Per API Billing", icon: Plug },
      { id: "billing-product", label: "Per Product Billing", icon: Package },
      { id: "billing-role", label: "Per Role Billing", icon: Users },
      { id: "billing-daily", label: "Daily Billing Summary", icon: Clock },
      { id: "billing-monthly", label: "Monthly Billing Summary", icon: Clock },
      { id: "billing-invoice", label: "Invoice Generator", icon: FileText },
      { id: "billing-allocation", label: "Billing Allocation", icon: TrendingUp },
    ],
  },
  {
    id: "alerts",
    label: "Alert & Safety System",
    icon: AlertTriangle,
    children: [
      { id: "alert-low-wallet", label: "Low Wallet Balance Alert", icon: Wallet },
      { id: "alert-overuse", label: "API Overuse Alert", icon: AlertCircle },
      { id: "alert-cost-spike", label: "Cost Spike Alert", icon: TrendingDown },
      { id: "alert-abnormal", label: "Abnormal Usage Alert", icon: AlertTriangle },
      { id: "alert-failure", label: "API Failure Alert", icon: AlertCircle },
      { id: "alert-security", label: "Security Breach Alert", icon: Shield },
      { id: "alert-runtime-errors", label: "Runtime Error Monitoring", icon: AlertCircle },
    ],
  },
  {
    id: "optimizer",
    label: "AI Cost Optimizer",
    icon: TrendingDown,
    children: [
      { id: "opt-high-cost", label: "Detect High-Cost APIs", icon: DollarSign },
      { id: "opt-cheaper", label: "Suggest Cheaper Alternative", icon: TrendingDown },
      { id: "opt-token", label: "Auto Reduce Token Usage", icon: Cpu },
      { id: "opt-downgrade", label: "Auto Downgrade Speed Mode", icon: Gauge },
      { id: "opt-recommendations", label: "Cost Saving Recommendations", icon: Sparkles },
    ],
  },
  {
    id: "security",
    label: "Security & Access",
    icon: Shield,
    children: [
      { id: "sec-logs", label: "API Access Logs", icon: FileText },
      { id: "sec-ip", label: "IP Restriction", icon: Shield },
      { id: "sec-region", label: "Region Restriction", icon: Map },
      { id: "sec-abuse", label: "Abuse Detection", icon: AlertTriangle },
      { id: "sec-block", label: "Manual Block Option", icon: Lock },
    ],
  },
  {
    id: "audit",
    label: "Audit & Logs",
    icon: FileText,
    children: [
      { id: "audit-api", label: "API On/Off Logs", icon: Power },
      { id: "audit-wallet", label: "Wallet Transaction Logs", icon: Wallet },
      { id: "audit-billing", label: "Billing Logs", icon: Receipt },
      { id: "audit-usage", label: "Usage Logs", icon: Activity },
      { id: "audit-admin", label: "Admin Action Logs", icon: Shield },
      { id: "audit-export", label: "Export Logs (CSV / JSON)", icon: Download },
    ],
  },
  {
    id: "emergency",
    label: "Emergency Controls",
    icon: Zap,
    children: [
      { id: "emg-kill-all", label: "Kill All APIs", icon: Skull },
      { id: "emg-kill-ai", label: "Kill AI APIs Only", icon: Bot },
      { id: "emg-lock-wallet", label: "Lock Wallet", icon: Lock },
      { id: "emg-resume", label: "Resume System", icon: Play },
      { id: "emg-incident", label: "Incident Report", icon: FileWarning },
    ],
  },
  {
    id: "registry",
    label: "API Registry & Ops",
    icon: Key,
    children: [
      { id: "reg-keys", label: "API Keys", icon: Key },
      { id: "reg-services", label: "API Services", icon: Plug },
      { id: "reg-integrations", label: "Integrations", icon: Boxes },
      { id: "reg-monitoring", label: "Monitoring & Health", icon: Activity },
      { id: "reg-rate-limits", label: "Rate Limits", icon: Gauge },
      { id: "reg-logs", label: "Request Logs", icon: ScrollText },
      { id: "reg-decisions", label: "AI Decision Logs", icon: Brain },
      { id: "reg-automation", label: "Automation Rules", icon: Zap },
      { id: "reg-reports", label: "Reports", icon: BarChart3 },
    ],
  },
  {
    id: "gateway",
    label: "Gateway Engine",
    icon: GitBranch,
    children: [
      { id: "gw-router", label: "Request Router", icon: GitBranch },
      { id: "gw-cache", label: "Response Cache", icon: Database },
      { id: "gw-failover", label: "Failover System", icon: RefreshCw },
    ],
  },
  {
    id: "governance",
    label: "AI Governance",
    icon: Brain,
    children: [
      { id: "gov-registry", label: "Model Registry", icon: Boxes },
      { id: "gov-agents", label: "AI Models & Agents", icon: Bot },
      { id: "gov-prompts", label: "Prompt Management", icon: MessageSquare },
      { id: "gov-finetune", label: "Fine-Tuning", icon: FlaskConical },
      { id: "gov-eval", label: "Model Evaluation", icon: BarChart3 },
      { id: "gov-safety", label: "AI Safety", icon: ShieldAlert },
      { id: "gov-data", label: "Data Governance", icon: FileText },
      { id: "gov-ondevice", label: "On-Device AI", icon: Smartphone },
      { id: "gov-lifecycle", label: "Version Lifecycle", icon: GitBranch },
      { id: "gov-incidents", label: "Incidents & Alerts", icon: AlertTriangle },
    ],
  },
  {
    id: "seo-manager",
    label: "Global SEO Tools",
    icon: Search,
    children: [
      { id: "seo-keywords", label: "Keyword Research", icon: Target },
      { id: "seo-rank-track", label: "Rank Tracking", icon: TrendingUp },
      { id: "seo-competitor", label: "Competitor Analysis", icon: Target },
      { id: "seo-backlink", label: "Backlink Monitor", icon: Link },
      { id: "seo-site-audit", label: "Site Audit", icon: BarChart3 },
      { id: "seo-content", label: "Content Optimization", icon: FileText },
      { id: "seo-schema", label: "Schema Markup", icon: Code },
      { id: "seo-local", label: "Local SEO", icon: Map },
    ],
  },
  {
    id: "lead-generator",
    label: "Lead Generation & CRM",
    icon: Target,
    children: [
      { id: "lead-finder", label: "Lead Finder", icon: Users },
      { id: "lead-email-scraper", label: "Email Scraper", icon: Mail },
      { id: "lead-linkedin", label: "LinkedIn Integration", icon: Users },
      { id: "lead-enrichment", label: "Lead Enrichment", icon: Sparkles },
      { id: "lead-scoring", label: "Lead Scoring & Qualification", icon: BarChart3 },
      { id: "lead-crm", label: "CRM Dashboard", icon: Activity },
      { id: "lead-campaigns", label: "Email Campaigns", icon: Mail },
      { id: "lead-analytics", label: "Lead Analytics", icon: BarChart3 },
    ],
  },
  {
    id: "traffic-automation",
    label: "Traffic & Automation",
    icon: TrendingUp,
    children: [
      { id: "traffic-analytics", label: "Traffic Analytics", icon: BarChart3 },
      { id: "traffic-sources", label: "Traffic Sources", icon: Plug },
      { id: "traffic-conversion", label: "Conversion Tracking", icon: Barcode },
      { id: "traffic-utm", label: "UTM Manager", icon: Tag },
      { id: "auto-reply", label: "Auto Reply System", icon: MessageSquare },
      { id: "auto-invoice", label: "Auto Invoice Generator", icon: Receipt },
      { id: "auto-email", label: "Auto Email Workflows", icon: Mail },
      { id: "auto-social", label: "Auto Social Posts", icon: MessageCircle },
    ],
  },
  {
    id: "ai-content",
    label: "AI Content Suite",
    icon: Sparkles,
    children: [
      { id: "content-generator", label: "Content Generator", icon: FileText },
      { id: "content-blog", label: "Blog Post Generator", icon: FileText },
      { id: "content-email", label: "Email Template Generator", icon: Mail },
      { id: "content-social", label: "Social Media Generator", icon: MessageCircle },
      { id: "content-seo-copy", label: "SEO Copy Writer", icon: Pen },
      { id: "content-image", label: "AI Image Generator", icon: Image },
      { id: "content-video", label: "Video Script Generator", icon: Video },
      { id: "content-translation", label: "Multi-Language Translator", icon: Globe },
    ],
  },
  {
    id: "subscription",
    label: "Subscriptions & Payments",
    icon: CreditCard,
    children: [
      { id: "sub-plans", label: "Subscription Plans", icon: Package },
      { id: "sub-manage", label: "Manage Subscriptions", icon: CreditCard },
      { id: "payment-methods", label: "Payment Methods", icon: CreditCard },
      { id: "invoices", label: "Invoices & Receipts", icon: FileText },
      { id: "billing-history", label: "Billing History", icon: Clock },
      { id: "coupons", label: "Coupons & Discounts", icon: Tag },
      { id: "payment-settings", label: "Payment Settings", icon: Settings },
      { id: "stripe-connect", label: "Stripe Connection", icon: CreditCard },
    ],
  },
  {
    id: "finance",
    label: "Finance Manager",
    icon: CircleDollarSign,
    children: [
      { id: "finance-overview", label: "Finance Dashboard", icon: LayoutDashboard },
      { id: "finance-invoices", label: "Invoices", icon: Receipt },
      { id: "finance-payments", label: "Payment Center", icon: CreditCard },
      { id: "finance-membership-payments", label: "Reseller Membership Payments", icon: CreditCard },
      { id: "finance-rails", label: "Payment Rails", icon: Landmark },
      { id: "finance-ledger", label: "Ledger", icon: ArrowDownUp },
      { id: "finance-reconciliation", label: "Reconciliation", icon: RefreshCw },
      { id: "finance-audit", label: "Audit Trail", icon: Shield },
    ],
  },
  {
    id: "cloud-connectors",
    label: "Cloud & Integrations",
    icon: Cloud,
    children: [
      { id: "cloud-google", label: "Google Cloud Setup", icon: Cloud },
      { id: "cloud-aws", label: "AWS Integration", icon: Cloud },
      { id: "cloud-azure", label: "Azure Setup", icon: Cloud },
      { id: "email-sendgrid", label: "SendGrid Email", icon: Mail },
      { id: "email-mailgun", label: "Mailgun Setup", icon: Mail },
      { id: "sms-twilio", label: "Twilio SMS", icon: MessageCircle },
      { id: "social-api", label: "Social Media APIs", icon: MessageCircle },
      { id: "storage-s3", label: "S3 Cloud Storage", icon: Database },
    ],
  },
  {
    id: "monitoring",
    label: "Self-Monitoring & Health",
    icon: Gauge,
    children: [
      { id: "health-check", label: "Health Check Status", icon: Gauge },
      { id: "uptime", label: "Uptime Monitor", icon: Activity },
      { id: "performance", label: "Performance Metrics", icon: TrendingUp },
      { id: "auto-healing", label: "Auto Healing System", icon: RefreshCw },
      { id: "alerts-system", label: "Alert Configuration", icon: Bell },
      { id: "logs-monitoring", label: "System Logs", icon: FileText },
      { id: "scaling", label: "Auto Scaling", icon: Gauge },
      { id: "backup-recovery", label: "Backup & Recovery", icon: Download },
    ],
  },
  {
    id: "settings",
    label: "Settings",
    icon: Settings,
    children: [
      { id: "settings-limits", label: "Default Limits", icon: Gauge },
      { id: "settings-thresholds", label: "Alert Thresholds", icon: AlertTriangle },
      { id: "settings-notifications", label: "Notification Preferences", icon: Bell },
      { id: "settings-all", label: "All Settings", icon: Settings },
    ],
  },
];

export const NAV_GROUP_IDS = MANAGER_NAV.map((g) => g.id);

export function findGroup(sectionId: string): NavGroup | undefined {
  return MANAGER_NAV.find(
    (g) => g.id === sectionId || g.children.some((c) => c.id === sectionId),
  );
}
