// Allowlist of manager tables reachable through the generic data server functions.
// Anything not listed here can never be read or written from the client.
export const MANAGER_TABLES = [
  "ai_providers",
  "api_services",
  "api_keys",
  "ai_models",
  "ai_agents",
  "api_integrations",
  "product_apis",
  "role_api_permissions",
  "rate_limits",
  "usage_events",
  "usage_daily",
  "billing_plans",
  "invoices",
  "wallets",
  "wallet_transactions",
  "cost_recommendations",
  "api_request_logs",
  "ai_decision_logs",
  "audit_logs",
  "security_alerts",
  "incidents",
  "automation_rules",
  "emergency_controls",
  "prompts",
  "prompt_versions",
  "fine_tuning_jobs",
  "model_evaluations",
  "safety_policies",
  "data_governance_rules",
  "on_device_models",
  "model_versions",
  "system_settings",
  "error_events",
  "router_rules",
  "cache_entries",
  "failover_events",
  "finance_payment_rails",
  "finance_customers",
  "finance_invoices",
  "finance_invoice_items",
  "finance_payment_intents",
  "finance_payments",
  "finance_payment_events",
  "finance_provider_transactions",
  "finance_reconciliation_records",
  "finance_ledger_entries",
  "finance_refunds",
  "finance_audit_logs",
  "finance_bank_transfers",
  "finance_currency_rates",
  "finance_payment_webhooks",
  "customer_finance_profiles",
  "reseller_membership_orders",
  "reseller_payment_intents",
  // Where the marketplace's real money lives. Orders, the lines within them,
  // the commission each line owes an author or vendor, refunds and payouts.
  // Finance could not see any of this: none of it was reachable through the
  // data layer, so the console showed API-usage billing and nothing else.
  "marketplace_orders",
  "marketplace_order_items",
  "marketplace_payment_intents",
  "marketplace_payment_events",
  "marketplace_order_refunds",
  "marketplace_commissions",
  "marketplace_commission_rules",
  "marketplace_commission_reversals",
  "marketplace_payouts",
  "marketplace_coupons",
  "marketplace_licenses",
  // The finance tables that actually carry rows. The list already had the
  // operational ones, which are all empty; these are the populated ones.
  "finance_transactions",
  "finance_subscriptions",
  "finance_plans",
  "finance_wallets",
  "finance_wallet_transactions",
  "finance_payouts",
  "finance_commissions",
  "finance_expenses",
  "finance_tax_records",
  "finance_daily_metrics",
  "finance_approvals",
  "finance_alerts",
  "finance_fraud_alerts",
  "finance_gateways",
  // Entitlement is what the buyer actually received for the money.
  "licenses",
  "entitlements",
] as const;

export type ManagerTable = (typeof MANAGER_TABLES)[number];

export function isManagerTable(value: string): value is ManagerTable {
  return (MANAGER_TABLES as readonly string[]).includes(value);
}
