DROP POLICY IF EXISTS "cat_read_all" ON public.achievement_categories;
CREATE POLICY "cat_read_all" ON public.achievement_categories FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "cat_admin_write" ON public.achievement_categories;
CREATE POLICY "cat_admin_write" ON public.achievement_categories FOR ALL TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "col_read_all" ON public.badge_collections;
CREATE POLICY "col_read_all" ON public.badge_collections FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "col_admin_write" ON public.badge_collections;
CREATE POLICY "col_admin_write" ON public.badge_collections FOR ALL TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "ach_read_all" ON public.achievements;
CREATE POLICY "ach_read_all" ON public.achievements FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "ach_admin_write" ON public.achievements;
CREATE POLICY "ach_admin_write" ON public.achievements FOR ALL TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "bdg_read_all" ON public.badges;
CREATE POLICY "bdg_read_all" ON public.badges FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "bdg_admin_write" ON public.badges;
CREATE POLICY "bdg_admin_write" ON public.badges FOR ALL TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "trp_read_all" ON public.trophies;
CREATE POLICY "trp_read_all" ON public.trophies FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "trp_admin_write" ON public.trophies;
CREATE POLICY "trp_admin_write" ON public.trophies FOR ALL TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "xpsrc_read" ON public.xp_sources;
CREATE POLICY "xpsrc_read" ON public.xp_sources FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "xpsrc_admin" ON public.xp_sources;
CREATE POLICY "xpsrc_admin" ON public.xp_sources FOR ALL TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "xprule_read" ON public.xp_rules;
CREATE POLICY "xprule_read" ON public.xp_rules FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "xprule_admin" ON public.xp_rules;
CREATE POLICY "xprule_admin" ON public.xp_rules FOR ALL TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "lvl_read" ON public.levels;
CREATE POLICY "lvl_read" ON public.levels FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "lvl_admin" ON public.levels;
CREATE POLICY "lvl_admin" ON public.levels FOR ALL TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "rnk_read" ON public.ranks;
CREATE POLICY "rnk_read" ON public.ranks FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "rnk_admin" ON public.ranks;
CREATE POLICY "rnk_admin" ON public.ranks FOR ALL TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "uxp_self" ON public.user_xp;
CREATE POLICY "uxp_self" ON public.user_xp FOR SELECT TO authenticated USING (user_id = auth.uid() OR public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "uxp_admin_write" ON public.user_xp;
CREATE POLICY "uxp_admin_write" ON public.user_xp FOR ALL TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "xptx_self_read" ON public.xp_transactions;
CREATE POLICY "xptx_self_read" ON public.xp_transactions FOR SELECT TO authenticated USING (user_id = auth.uid() OR public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "xptx_admin_write" ON public.xp_transactions;
CREATE POLICY "xptx_admin_write" ON public.xp_transactions FOR ALL TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "uach_self_read" ON public.user_achievements;
CREATE POLICY "uach_self_read" ON public.user_achievements FOR SELECT TO authenticated USING (user_id = auth.uid() OR public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "uach_admin_write" ON public.user_achievements;
CREATE POLICY "uach_admin_write" ON public.user_achievements FOR ALL TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "ubdg_self_read" ON public.user_badges;
CREATE POLICY "ubdg_self_read" ON public.user_badges FOR SELECT TO authenticated USING (user_id = auth.uid() OR public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "ubdg_admin_write" ON public.user_badges;
CREATE POLICY "ubdg_admin_write" ON public.user_badges FOR ALL TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "utrp_self_read" ON public.user_trophies;
CREATE POLICY "utrp_self_read" ON public.user_trophies FOR SELECT TO authenticated USING (user_id = auth.uid() OR public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "utrp_admin_write" ON public.user_trophies;
CREATE POLICY "utrp_admin_write" ON public.user_trophies FOR ALL TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "ustr_self_read" ON public.user_streaks;
CREATE POLICY "ustr_self_read" ON public.user_streaks FOR SELECT TO authenticated USING (user_id = auth.uid() OR public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "ustr_admin_write" ON public.user_streaks;
CREATE POLICY "ustr_admin_write" ON public.user_streaks FOR ALL TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "ssn_read" ON public.seasons;
CREATE POLICY "ssn_read" ON public.seasons FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "ssn_admin" ON public.seasons;
CREATE POLICY "ssn_admin" ON public.seasons FOR ALL TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "cmp_read" ON public.campaigns;
CREATE POLICY "cmp_read" ON public.campaigns FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "cmp_admin" ON public.campaigns;
CREATE POLICY "cmp_admin" ON public.campaigns FOR ALL TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "evt_read" ON public.events;
CREATE POLICY "evt_read" ON public.events FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "evt_admin" ON public.events;
CREATE POLICY "evt_admin" ON public.events FOR ALL TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "msn_read" ON public.missions;
CREATE POLICY "msn_read" ON public.missions FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "msn_admin" ON public.missions;
CREATE POLICY "msn_admin" ON public.missions FOR ALL TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "qst_read" ON public.quests;
CREATE POLICY "qst_read" ON public.quests FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "qst_admin" ON public.quests;
CREATE POLICY "qst_admin" ON public.quests FOR ALL TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "chl_read" ON public.challenges;
CREATE POLICY "chl_read" ON public.challenges FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "chl_admin" ON public.challenges;
CREATE POLICY "chl_admin" ON public.challenges FOR ALL TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "ump_self_read" ON public.user_mission_progress;
CREATE POLICY "ump_self_read" ON public.user_mission_progress FOR SELECT TO authenticated USING (user_id = auth.uid() OR public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "ump_admin_write" ON public.user_mission_progress;
CREATE POLICY "ump_admin_write" ON public.user_mission_progress FOR ALL TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "rwd_read" ON public.rewards;
CREATE POLICY "rwd_read" ON public.rewards FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "rwd_admin" ON public.rewards;
CREATE POLICY "rwd_admin" ON public.rewards FOR ALL TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "wal_self_read" ON public.reward_wallets;
CREATE POLICY "wal_self_read" ON public.reward_wallets FOR SELECT TO authenticated USING (user_id = auth.uid() OR public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "wal_admin_write" ON public.reward_wallets;
CREATE POLICY "wal_admin_write" ON public.reward_wallets FOR ALL TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "clm_self_read" ON public.claims;
CREATE POLICY "clm_self_read" ON public.claims FOR SELECT TO authenticated USING (user_id = auth.uid() OR public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "clm_self_insert" ON public.claims;
CREATE POLICY "clm_self_insert" ON public.claims FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
DROP POLICY IF EXISTS "clm_admin_update" ON public.claims;
CREATE POLICY "clm_admin_update" ON public.claims FOR UPDATE TO authenticated USING (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "clm_admin_delete" ON public.claims;
CREATE POLICY "clm_admin_delete" ON public.claims FOR DELETE TO authenticated USING (public.has_role(auth.uid(),'super_admin'));
DROP POLICY IF EXISTS "lbd_read" ON public.leaderboard_definitions;
CREATE POLICY "lbd_read" ON public.leaderboard_definitions FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "lbd_admin" ON public.leaderboard_definitions;
CREATE POLICY "lbd_admin" ON public.leaderboard_definitions FOR ALL TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "lbe_read" ON public.leaderboard_entries;
CREATE POLICY "lbe_read" ON public.leaderboard_entries FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "lbe_admin_write" ON public.leaderboard_entries;
CREATE POLICY "lbe_admin_write" ON public.leaderboard_entries FOR ALL TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "ntpl_read" ON public.notification_templates;
CREATE POLICY "ntpl_read" ON public.notification_templates FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "ntpl_admin" ON public.notification_templates;
CREATE POLICY "ntpl_admin" ON public.notification_templates FOR ALL TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "nrul_read" ON public.notification_rules;
CREATE POLICY "nrul_read" ON public.notification_rules FOR SELECT TO authenticated USING (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "nrul_admin" ON public.notification_rules;
CREATE POLICY "nrul_admin" ON public.notification_rules FOR ALL TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "nfy_self_read" ON public.notifications;
CREATE POLICY "nfy_self_read" ON public.notifications FOR SELECT TO authenticated USING (user_id = auth.uid() OR public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "nfy_self_update" ON public.notifications;
CREATE POLICY "nfy_self_update" ON public.notifications FOR UPDATE TO authenticated USING (user_id = auth.uid());
DROP POLICY IF EXISTS "nfy_admin_write" ON public.notifications;
CREATE POLICY "nfy_admin_write" ON public.notifications FOR INSERT TO authenticated WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "nfy_admin_del" ON public.notifications;
CREATE POLICY "nfy_admin_del" ON public.notifications FOR DELETE TO authenticated USING (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "act_admin_read" ON public.activity_logs;
CREATE POLICY "act_admin_read" ON public.activity_logs FOR SELECT TO authenticated USING (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "act_self_read" ON public.activity_logs;
CREATE POLICY "act_self_read" ON public.activity_logs FOR SELECT TO authenticated USING (user_id = auth.uid());
DROP POLICY IF EXISTS "ane_admin_read" ON public.analytics_events;
CREATE POLICY "ane_admin_read" ON public.analytics_events FOR SELECT TO authenticated USING (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "aip_admin" ON public.ai_prompts;
CREATE POLICY "aip_admin" ON public.ai_prompts FOR ALL TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));